theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

title: [Marine Le Gall]
description: [Présentation de mes projets]
show_downloads: ["true"]
logo: ./logo.png
autor: Marine Le Gall
email: your-email@domain.com
