theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


title: [Marine Le Gall]
description: [Présentation de mes projets, contact : marine-legall @ orange.fr]
logo: /logo.png
show_downloads: true


