theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


title: Marine Le Gall
description: marinelg@protonmail.com
logo: /logo.png
show_downloads: true


